### ISSUE TITLE
Support for laravel 10

### ISSUE THREAD

**Issue by lakuapik** [filipfonal/filament-log-manager#9]
thank you for this great package!

unfornately when i try to install in laravel v10, i got this error:

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/20186786/220008147-a4862e07-7158-4b07-a4b7-c57e5ff1f95a.png">

**Comment by filipfonal** [comment]
Thanks for this report. Support for laravel 10 added to the new release: https://github.com/filipfonal/filament-log-manager/releases/tag/1.2.0
